/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.luisev.tareas.ui;

import com.toedter.calendar.JDateChooser;
import es.luisev.tareas.model.*;
import es.luisev.tareas.ui.listener.MantenimientoFiltroListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class MantenimientoFiltroDialog extends DialogoBase {

    /**
     * Creates new form FiltroDialog
     *
     * @param parent
     * @param paramObject
     */
    public MantenimientoFiltroDialog(VisorForm parent, Object paramObject) {
        super(parent, paramObject);
    }

    public MantenimientoFiltroDialog(VisorForm frame, Object paramObject, boolean modal) {
        super(frame, paramObject, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategoria = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblSubCategoria = new javax.swing.JLabel();
        cmbSubCategoria = new javax.swing.JComboBox<>();
        lblPeticion = new javax.swing.JLabel();
        cmbPeticion = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        pnlPeticion = new javax.swing.JPanel();
        lblAsuntoContiene = new javax.swing.JLabel();
        txtAsuntoContiene = new javax.swing.JTextField();
        lblInicioPrevisto = new javax.swing.JLabel();
        dchInicioPrevistoDesde = new com.toedter.calendar.JDateChooser();
        dchInicioPrevistoHasta = new com.toedter.calendar.JDateChooser();
        lblFinPrevisto = new javax.swing.JLabel();
        dchFinPrevistoDesde = new com.toedter.calendar.JDateChooser();
        dchFinPrevistoHasta = new com.toedter.calendar.JDateChooser();
        lblInicioReal = new javax.swing.JLabel();
        dchInicioRealDesde = new com.toedter.calendar.JDateChooser();
        dchInicioRealHasta = new com.toedter.calendar.JDateChooser();
        lblFinReal = new javax.swing.JLabel();
        dchFinRealDesde = new com.toedter.calendar.JDateChooser();
        dchFinRealHasta = new com.toedter.calendar.JDateChooser();
        lblHorasPrevista = new javax.swing.JLabel();
        txtHorasPrevistaDesde = new javax.swing.JTextField();
        txtHorasPrevistaHasta = new javax.swing.JTextField();
        lblHorasReal = new javax.swing.JLabel();
        txtHorasRealDesde = new javax.swing.JTextField();
        txtHorasRealHasta = new javax.swing.JTextField();
        lblPorcentaje = new javax.swing.JLabel();
        txtPorcentajeDesde = new javax.swing.JTextField();
        txtPorcentajeHasta = new javax.swing.JTextField();
        cmbUsuario = new javax.swing.JComboBox<>();
        lblUsuario = new javax.swing.JLabel();
        pnlImputacion = new javax.swing.JPanel();
        lblFechaImputacion = new javax.swing.JLabel();
        dchFechaImputacionDesde = new com.toedter.calendar.JDateChooser();
        dchFechaImputacionHasta = new com.toedter.calendar.JDateChooser();
        lblHorasImputadas = new javax.swing.JLabel();
        txtHorasImputadasDesde = new javax.swing.JTextField();
        txtHorasImputadasHasta = new javax.swing.JTextField();
        lblTipoHoras = new javax.swing.JLabel();
        cmbTipoHoras = new javax.swing.JComboBox<>();
        pnlDocumento = new javax.swing.JPanel();
        lblTipoDocumento = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        lblNombreContiene = new javax.swing.JLabel();
        txtNombreContiene = new javax.swing.JTextField();
        lblRuta = new javax.swing.JLabel();
        btnRuta = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCategoria.setText("Categoria");

        cmbCategoria.setToolTipText("");

        lblSubCategoria.setText("SubCategoría");

        cmbSubCategoria.setToolTipText("");

        lblPeticion.setText("Petición");

        cmbPeticion.setToolTipText("");

        lblEstado.setText("Estado");

        javax.swing.GroupLayout pnlCategoriaLayout = new javax.swing.GroupLayout(pnlCategoria);
        pnlCategoria.setLayout(pnlCategoriaLayout);
        pnlCategoriaLayout.setHorizontalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSubCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(lblPeticion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCategoriaLayout.createSequentialGroup()
                        .addComponent(cmbPeticion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCategoriaLayout.setVerticalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlPeticion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAsuntoContiene.setText("Contiene en sus textos");

        lblInicioPrevisto.setText("Fecha Inicio Previsto");

        dchInicioPrevistoDesde.setDateFormatString("dd/MM/yyyy");

        dchInicioPrevistoHasta.setDateFormatString("dd/MM/yyyy");

        lblFinPrevisto.setText("Fecha Fin Previsto");

        dchFinPrevistoDesde.setDateFormatString("dd/MM/yyyy");

        dchFinPrevistoHasta.setDateFormatString("dd/MM/yyyy");

        lblInicioReal.setText("Fecha Inicio Real");

        dchInicioRealDesde.setDateFormatString("dd/MM/yyyy");

        dchInicioRealHasta.setDateFormatString("dd/MM/yyyy");

        lblFinReal.setText("Fecha Fin Real");

        dchFinRealDesde.setDateFormatString("dd/MM/yyyy");

        dchFinRealHasta.setDateFormatString("dd/MM/yyyy");

        lblHorasPrevista.setText("Horas Previstas");

        lblHorasReal.setText("Horas Reales");

        lblPorcentaje.setText("Porcentaje de realización ");
        lblPorcentaje.setToolTipText("");

        cmbUsuario.setToolTipText("");

        lblUsuario.setText("Usuario");

        javax.swing.GroupLayout pnlPeticionLayout = new javax.swing.GroupLayout(pnlPeticion);
        pnlPeticion.setLayout(pnlPeticionLayout);
        pnlPeticionLayout.setHorizontalGroup(
            pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeticionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInicioPrevisto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPeticionLayout.createSequentialGroup()
                                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtHorasPrevistaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPorcentajeDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(23, 23, 23)
                                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtHorasPrevistaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPorcentajeHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addComponent(dchInicioPrevistoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dchInicioPrevistoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addComponent(dchInicioRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dchInicioRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(220, 220, 220)
                                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addComponent(lblFinReal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dchFinRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dchFinRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPeticionLayout.createSequentialGroup()
                                            .addComponent(lblHorasReal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtHorasRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(23, 23, 23)
                                            .addComponent(txtHorasRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlPeticionLayout.createSequentialGroup()
                                            .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(pnlPeticionLayout.createSequentialGroup()
                                                    .addComponent(lblFinPrevisto, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(dchFinPrevistoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(dchFinPrevistoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPeticionLayout.createSequentialGroup()
                                                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cmbUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGap(0, 0, 0)))))
                            .addComponent(txtAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblInicioReal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorasPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPeticionLayout.setVerticalGroup(
            pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeticionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblInicioPrevisto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFinPrevisto))
                    .addComponent(dchInicioPrevistoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchInicioPrevistoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchFinPrevistoDesde, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchFinPrevistoHasta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInicioReal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchInicioRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchInicioRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchFinRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchFinRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinReal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasPrevista, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasPrevistaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasPrevistaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorasReal)
                    .addComponent(txtHorasRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcentajeDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPorcentajeHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnlImputacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFechaImputacion.setText("Fecha Imputación");

        dchFechaImputacionDesde.setDateFormatString("dd-MM-yyyy");

        dchFechaImputacionHasta.setDateFormatString("dd-MM-yyyy");

        lblHorasImputadas.setText("Horas Imputadas ");

        lblTipoHoras.setText("Tipo Horas");

        cmbTipoHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Normales", "Extra" }));

        javax.swing.GroupLayout pnlImputacionLayout = new javax.swing.GroupLayout(pnlImputacion);
        pnlImputacion.setLayout(pnlImputacionLayout);
        pnlImputacionLayout.setHorizontalGroup(
            pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImputacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaImputacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dchFechaImputacionDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dchFechaImputacionHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(lblHorasImputadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHorasImputadasDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHorasImputadasHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180)
                .addComponent(lblTipoHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlImputacionLayout.setVerticalGroup(
            pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImputacionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dchFechaImputacionHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dchFechaImputacionDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaImputacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHorasImputadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHorasImputadasDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtHorasImputadasHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbTipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pnlDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTipoDocumento.setText("Tipo Documento");

        lblNombreContiene.setText("Nombre contiene");

        lblRuta.setText("Ruta documento");

        btnRuta.setText("jButton1");

        javax.swing.GroupLayout pnlDocumentoLayout = new javax.swing.GroupLayout(pnlDocumento);
        pnlDocumento.setLayout(pnlDocumentoLayout);
        pnlDocumentoLayout.setHorizontalGroup(
            pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTipoDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDocumentoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDocumentoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNombreContiene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDocumentoLayout.setVerticalGroup(
            pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDocumentoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(65, 65));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(65, 65));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(105, 41));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btnGuardar.setText("Guardar");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida_32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImputacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(pnlPeticion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImputacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRuta;
    private javax.swing.JComboBox<Categoria> cmbCategoria;
    private javax.swing.JComboBox<Estado> cmbEstado;
    private javax.swing.JComboBox<Peticion> cmbPeticion;
    private javax.swing.JComboBox<SubCategoria> cmbSubCategoria;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JComboBox<String> cmbTipoHoras;
    private javax.swing.JComboBox<Usuario> cmbUsuario;
    private com.toedter.calendar.JDateChooser dchFechaImputacionDesde;
    private com.toedter.calendar.JDateChooser dchFechaImputacionHasta;
    private com.toedter.calendar.JDateChooser dchFinPrevistoDesde;
    private com.toedter.calendar.JDateChooser dchFinPrevistoHasta;
    private com.toedter.calendar.JDateChooser dchFinRealDesde;
    private com.toedter.calendar.JDateChooser dchFinRealHasta;
    private com.toedter.calendar.JDateChooser dchInicioPrevistoDesde;
    private com.toedter.calendar.JDateChooser dchInicioPrevistoHasta;
    private com.toedter.calendar.JDateChooser dchInicioRealDesde;
    private com.toedter.calendar.JDateChooser dchInicioRealHasta;
    private javax.swing.JLabel lblAsuntoContiene;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechaImputacion;
    private javax.swing.JLabel lblFinPrevisto;
    private javax.swing.JLabel lblFinReal;
    private javax.swing.JLabel lblHorasImputadas;
    private javax.swing.JLabel lblHorasPrevista;
    private javax.swing.JLabel lblHorasReal;
    private javax.swing.JLabel lblInicioPrevisto;
    private javax.swing.JLabel lblInicioReal;
    private javax.swing.JLabel lblNombreContiene;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblPorcentaje;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblSubCategoria;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JLabel lblTipoHoras;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlDocumento;
    private javax.swing.JPanel pnlImputacion;
    private javax.swing.JPanel pnlPeticion;
    private javax.swing.JTextField txtAsuntoContiene;
    private javax.swing.JTextField txtHorasImputadasDesde;
    private javax.swing.JTextField txtHorasImputadasHasta;
    private javax.swing.JTextField txtHorasPrevistaDesde;
    private javax.swing.JTextField txtHorasPrevistaHasta;
    private javax.swing.JTextField txtHorasRealDesde;
    private javax.swing.JTextField txtHorasRealHasta;
    private javax.swing.JTextField txtNombreContiene;
    private javax.swing.JTextField txtPorcentajeDesde;
    private javax.swing.JTextField txtPorcentajeHasta;
    private javax.swing.JTextField txtRuta;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void initLiterals() {
        setTitulo();
    }

    @Override
    protected void initListener() {
        initComponents();
        MantenimientoFiltroListener listener = new MantenimientoFiltroListener(this);
        btnGuardar.addActionListener(listener);
        btnCancelar.addActionListener(listener);
        btnLimpiar.addActionListener(listener);
    }

   /* private void addRangoMouseListener(JTextField txtField) {
        RangoFechaFocusListener listener = new RangoFechaFocusListener(this, txtField);
        txtField.addFocusListener(listener);
    }*/

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    @Override
    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    //************************************************
    // Elementos de pantalla
    //*************************************************
    public JButton getBtnRuta() {
        return btnRuta;
    }

    public JComboBox<Estado> getCmbEstado() {
        return cmbEstado;
    }

    public JComboBox<Categoria> getCmbCategoria() {
        return cmbCategoria;
    }

    public JComboBox<Peticion> getCmbPeticion() {
        return cmbPeticion;
    }

    public JComboBox<SubCategoria> getCmbSubCategoria() {
        return cmbSubCategoria;
    }

    public JComboBox<String> getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public JComboBox<String> getCmbTipoHoras() {
        return cmbTipoHoras;
    }

    public JComboBox<Usuario> getCmbUsuario() {
        return cmbUsuario;
    }

    public JTextField getTxtAsuntoContiene() {
        return txtAsuntoContiene;
    }

    public JDateChooser getDchFinPrevistoDesde() {
        return dchFinPrevistoDesde;
    }

    public JDateChooser getDchFinPrevistoHasta() {
        return dchFinPrevistoHasta;
    }

    public JDateChooser getDchFinRealDesde() {
        return dchFinRealDesde;
    }

    public JDateChooser getDchFinRealHasta() {
        return dchFinRealHasta;
    }

    public JDateChooser getDchImputacionDesde() {
        return dchFechaImputacionDesde;
    }

    public JDateChooser getDchImputacionHasta() {
        return dchFechaImputacionHasta;
    }

    public JDateChooser getDchFechaImputacionDesde() {
        return dchFechaImputacionDesde;
    }

    public JDateChooser getDchFechaImputacionHasta() {
        return dchFechaImputacionHasta;
    }

    public JDateChooser getDchInicioPrevistoDesde() {
        return dchInicioPrevistoDesde;
    }

    public JDateChooser getDchInicioPrevistoHasta() {
        return dchInicioPrevistoHasta;
    }

    public JDateChooser getDchInicioRealDesde() {
        return dchInicioRealDesde;
    }

    public JDateChooser getDchInicioRealHasta() {
        return dchInicioRealHasta;
    }

    public JTextField getTxtHorasImputadasDesde() {
        return txtHorasImputadasDesde;
    }

    public JTextField getTxtHorasImputadasHasta() {
        return txtHorasImputadasHasta;
    }

    public JTextField getTxtHorasPrevistaDesde() {
        return txtHorasPrevistaDesde;
    }

    public JTextField getTxtHorasPrevistaHasta() {
        return txtHorasPrevistaHasta;
    }

    public JTextField getTxtHorasRealesDesde() {
        return txtHorasRealDesde;
    }

    public JTextField getTxtHorasRealesHasta() {
        return txtHorasRealHasta;
    }

    public JTextField getTxtNombreContiene() {
        return txtNombreContiene;
    }

    public JTextField getTxtRuta() {
        return txtRuta;
    }

    public JTextField getTxtPorcentajeDesde() {
        return txtPorcentajeDesde;
    }

    public JTextField getTxtPorcentajeHasta() {
        return txtPorcentajeHasta;
    }
}
