/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.luisev.tareas.ui;

import es.luisev.tareas.model.*;
import es.luisev.tareas.ui.listener.MantenimientoFiltroListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author Luis-Enrique.Varona
 */
public class MantenimientoFiltroDialog extends DialogoBase {

    /**
     * Creates new form FiltroDialog
     *
     * @param parent
     * @param paramObject
     */
    public MantenimientoFiltroDialog(JFrame parent, DataBaseEntity paramObject) {
        super(parent, paramObject);
    }

    /**
     * Creates new form FiltroDialog
     * @param parent
     */
    public MantenimientoFiltroDialog(JFrame parent) {
        this(parent, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCategoria = new javax.swing.JPanel();
        lblCategoria = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        lblSubCategoria = new javax.swing.JLabel();
        cmbSubCategoria = new javax.swing.JComboBox<>();
        lblPeticion = new javax.swing.JLabel();
        cmbPeticion = new javax.swing.JComboBox<>();
        pnlEstados = new javax.swing.JPanel();
        chkPendiente = new javax.swing.JCheckBox();
        chkEnCurso = new javax.swing.JCheckBox();
        chkRetenida = new javax.swing.JCheckBox();
        chkAnulada = new javax.swing.JCheckBox();
        chkFinalizada = new javax.swing.JCheckBox();
        chkCerrada = new javax.swing.JCheckBox();
        pnlPeticion = new javax.swing.JPanel();
        lblAsuntoContiene = new javax.swing.JLabel();
        txtAsuntoContiene = new javax.swing.JTextField();
        lblFechaInicioProgramado = new javax.swing.JLabel();
        txtFechaInicioProgramadoDesde = new javax.swing.JTextField();
        txtFechaInicioProgramadoHasta = new javax.swing.JTextField();
        lblFechaFinProgramado = new javax.swing.JLabel();
        txtFechaFinProgramadoDesde = new javax.swing.JTextField();
        txtFechaFinProgramadoHasta = new javax.swing.JTextField();
        lblFechaInicioReal = new javax.swing.JLabel();
        txtFechaInicioRealDesde = new javax.swing.JTextField();
        txtFechaInicioRealHasta = new javax.swing.JTextField();
        lblFechaFinReal = new javax.swing.JLabel();
        txtFechaFinRealDesde = new javax.swing.JTextField();
        txtFechaFinRealHasta = new javax.swing.JTextField();
        lblHorasProgramadas = new javax.swing.JLabel();
        txtHorasProgramadasDesde = new javax.swing.JTextField();
        txtHorasProgramadasHasta = new javax.swing.JTextField();
        lblHorasReales = new javax.swing.JLabel();
        txtHorasRealesDesde = new javax.swing.JTextField();
        txtHorasRealesHasta = new javax.swing.JTextField();
        lblPorcentajeRealizacion = new javax.swing.JLabel();
        txtlPorcentajeRealizacionDesde = new javax.swing.JTextField();
        txtlPorcentajeRealizacionHasta = new javax.swing.JTextField();
        cmbUsuario = new javax.swing.JComboBox<>();
        lblUsuario = new javax.swing.JLabel();
        pnlImputacion = new javax.swing.JPanel();
        lblFechaImputacion = new javax.swing.JLabel();
        txtFechaImputacionDesde = new javax.swing.JTextField();
        txtFechaImputacionHasta = new javax.swing.JTextField();
        cmbPeriodoFecha = new javax.swing.JComboBox<>();
        lblHorasImputadas = new javax.swing.JLabel();
        txtHorasImputadasDesde = new javax.swing.JTextField();
        txtHorasImputadasHasta = new javax.swing.JTextField();
        lblTipoHoras = new javax.swing.JLabel();
        cmbTipoHoras = new javax.swing.JComboBox<>();
        pnlDocumento = new javax.swing.JPanel();
        lblTipoDocumento = new javax.swing.JLabel();
        cmbTipoDocumento = new javax.swing.JComboBox<>();
        lblNombreContiene = new javax.swing.JLabel();
        txtNombreContiene = new javax.swing.JTextField();
        lblRuta = new javax.swing.JLabel();
        btnRuta = new javax.swing.JButton();
        txtRuta = new javax.swing.JTextField();
        pnlBotones = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCategoria.setText("Categoria");

        cmbCategoria.setToolTipText("");

        lblSubCategoria.setText("SubCategoría");

        cmbSubCategoria.setToolTipText("");

        lblPeticion.setText("Petición");

        cmbPeticion.setToolTipText("");

        javax.swing.GroupLayout pnlCategoriaLayout = new javax.swing.GroupLayout(pnlCategoria);
        pnlCategoria.setLayout(pnlCategoriaLayout);
        pnlCategoriaLayout.setHorizontalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbSubCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPeticion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCategoriaLayout.setVerticalGroup(
            pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCategoriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chkPendiente.setText("Pendiente");

        chkEnCurso.setText("En curso");

        chkRetenida.setText("Retenida");

        chkAnulada.setText("Anulada");

        chkFinalizada.setText("Finalizada");

        chkCerrada.setText("Cerrada");

        javax.swing.GroupLayout pnlEstadosLayout = new javax.swing.GroupLayout(pnlEstados);
        pnlEstados.setLayout(pnlEstadosLayout);
        pnlEstadosLayout.setHorizontalGroup(
            pnlEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkPendiente)
                .addGap(100, 100, 100)
                .addComponent(chkEnCurso)
                .addGap(100, 100, 100)
                .addComponent(chkRetenida)
                .addGap(102, 102, 102)
                .addComponent(chkAnulada)
                .addGap(94, 94, 94)
                .addComponent(chkFinalizada)
                .addGap(81, 81, 81)
                .addComponent(chkCerrada)
                .addContainerGap())
        );
        pnlEstadosLayout.setVerticalGroup(
            pnlEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEstadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPendiente)
                    .addComponent(chkAnulada)
                    .addComponent(chkCerrada)
                    .addComponent(chkFinalizada)
                    .addComponent(chkEnCurso)
                    .addComponent(chkRetenida))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pnlPeticion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblAsuntoContiene.setText("Contiene en sus textos");

        lblFechaInicioProgramado.setText("Fecha Inicio Programado ");

        lblFechaFinProgramado.setText("Fecha Fin Programado ");

        lblFechaInicioReal.setText("Fecha Inicio Real");

        lblFechaFinReal.setText("Fecha Fin Real");

        lblHorasProgramadas.setText("Horas Programadas ");

        lblHorasReales.setText("Horas Reales");

        lblPorcentajeRealizacion.setText("Porcentaje de realización ");
        lblPorcentajeRealizacion.setToolTipText("");

        cmbUsuario.setToolTipText("");

        lblUsuario.setText("Usuario");

        javax.swing.GroupLayout pnlPeticionLayout = new javax.swing.GroupLayout(pnlPeticion);
        pnlPeticion.setLayout(pnlPeticionLayout);
        pnlPeticionLayout.setHorizontalGroup(
            pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeticionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaInicioProgramado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPeticionLayout.createSequentialGroup()
                                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtFechaInicioRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHorasProgramadasDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtlPorcentajeRealizacionDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHorasProgramadasHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaInicioRealHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtlPorcentajeRealizacionHasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addComponent(txtFechaInicioProgramadoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaInicioProgramadoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(10, 10, 10)
                                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlPeticionLayout.createSequentialGroup()
                                                .addComponent(lblFechaFinReal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFechaFinRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlPeticionLayout.createSequentialGroup()
                                                .addComponent(lblHorasReales, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtHorasRealesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHorasRealesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFechaFinRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pnlPeticionLayout.createSequentialGroup()
                                        .addComponent(lblFechaFinProgramado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFechaFinProgramadoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtFechaFinProgramadoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlPeticionLayout.createSequentialGroup()
                                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(lblFechaInicioReal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorasProgramadas, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPorcentajeRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPeticionLayout.setVerticalGroup(
            pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPeticionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAsuntoContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicioProgramado, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicioProgramadoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicioProgramadoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFinProgramado)
                    .addComponent(txtFechaFinProgramadoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFinProgramadoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaInicioReal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicioRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaInicioRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFechaFinReal)
                    .addComponent(txtFechaFinRealDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaFinRealHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHorasProgramadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasProgramadasDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasProgramadasHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorasReales)
                    .addComponent(txtHorasRealesDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasRealesHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPeticionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcentajeRealizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlPorcentajeRealizacionDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtlPorcentajeRealizacionHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pnlImputacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFechaImputacion.setText("Fecha Imputación");

        lblHorasImputadas.setText("Horas Imputadas ");

        lblTipoHoras.setText("Tipo Horas");

        cmbTipoHoras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Normales", "Extra" }));

        javax.swing.GroupLayout pnlImputacionLayout = new javax.swing.GroupLayout(pnlImputacion);
        pnlImputacion.setLayout(pnlImputacionLayout);
        pnlImputacionLayout.setHorizontalGroup(
            pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImputacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFechaImputacion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFechaImputacionDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFechaImputacionHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbPeriodoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(lblHorasImputadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHorasImputadasDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHorasImputadasHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblTipoHoras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlImputacionLayout.setVerticalGroup(
            pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlImputacionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlImputacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaImputacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaImputacionDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaImputacionHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHorasImputadas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasImputadasDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorasImputadasHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPeriodoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTipoDocumento.setText("Tipo Documento");

        lblNombreContiene.setText("Nombre contiene");

        lblRuta.setText("Ruta documento");

        btnRuta.setText("jButton1");

        javax.swing.GroupLayout pnlDocumentoLayout = new javax.swing.GroupLayout(pnlDocumento);
        pnlDocumento.setLayout(pnlDocumentoLayout);
        pnlDocumentoLayout.setHorizontalGroup(
            pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDocumentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDocumentoLayout.createSequentialGroup()
                        .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRuta))
                    .addGroup(pnlDocumentoLayout.createSequentialGroup()
                        .addComponent(lblTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(lblNombreContiene)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreContiene)))
                .addContainerGap())
        );
        pnlDocumentoLayout.setVerticalGroup(
            pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDocumentoLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreContiene, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDocumentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/limpiar.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setToolTipText("");
        btnLimpiar.setMaximumSize(new java.awt.Dimension(65, 65));
        btnLimpiar.setMinimumSize(new java.awt.Dimension(65, 65));
        btnLimpiar.setPreferredSize(new java.awt.Dimension(105, 41));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salvar.png"))); // NOI18N
        btnGuardar.setText("Guardar");

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/salida_32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(215, 215, 215)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCategoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlImputacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlPeticion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlImputacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRuta;
    private javax.swing.JCheckBox chkAnulada;
    private javax.swing.JCheckBox chkCerrada;
    private javax.swing.JCheckBox chkEnCurso;
    private javax.swing.JCheckBox chkFinalizada;
    private javax.swing.JCheckBox chkPendiente;
    private javax.swing.JCheckBox chkRetenida;
    private javax.swing.JComboBox<Categoria> cmbCategoria;
    private javax.swing.JComboBox<String> cmbPeriodoFecha;
    private javax.swing.JComboBox<Peticion> cmbPeticion;
    private javax.swing.JComboBox<SubCategoria> cmbSubCategoria;
    private javax.swing.JComboBox<String> cmbTipoDocumento;
    private javax.swing.JComboBox<String> cmbTipoHoras;
    private javax.swing.JComboBox<Usuario> cmbUsuario;
    private javax.swing.JLabel lblAsuntoContiene;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblFechaFinProgramado;
    private javax.swing.JLabel lblFechaFinReal;
    private javax.swing.JLabel lblFechaImputacion;
    private javax.swing.JLabel lblFechaInicioProgramado;
    private javax.swing.JLabel lblFechaInicioReal;
    private javax.swing.JLabel lblHorasImputadas;
    private javax.swing.JLabel lblHorasProgramadas;
    private javax.swing.JLabel lblHorasReales;
    private javax.swing.JLabel lblNombreContiene;
    private javax.swing.JLabel lblPeticion;
    private javax.swing.JLabel lblPorcentajeRealizacion;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JLabel lblSubCategoria;
    private javax.swing.JLabel lblTipoDocumento;
    private javax.swing.JLabel lblTipoHoras;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlCategoria;
    private javax.swing.JPanel pnlDocumento;
    private javax.swing.JPanel pnlEstados;
    private javax.swing.JPanel pnlImputacion;
    private javax.swing.JPanel pnlPeticion;
    private javax.swing.JTextField txtAsuntoContiene;
    private javax.swing.JTextField txtFechaFinProgramadoDesde;
    private javax.swing.JTextField txtFechaFinProgramadoHasta;
    private javax.swing.JTextField txtFechaFinRealDesde;
    private javax.swing.JTextField txtFechaFinRealHasta;
    private javax.swing.JTextField txtFechaImputacionDesde;
    private javax.swing.JTextField txtFechaImputacionHasta;
    private javax.swing.JTextField txtFechaInicioProgramadoDesde;
    private javax.swing.JTextField txtFechaInicioProgramadoHasta;
    private javax.swing.JTextField txtFechaInicioRealDesde;
    private javax.swing.JTextField txtFechaInicioRealHasta;
    private javax.swing.JTextField txtHorasImputadasDesde;
    private javax.swing.JTextField txtHorasImputadasHasta;
    private javax.swing.JTextField txtHorasProgramadasDesde;
    private javax.swing.JTextField txtHorasProgramadasHasta;
    private javax.swing.JTextField txtHorasRealesDesde;
    private javax.swing.JTextField txtHorasRealesHasta;
    private javax.swing.JTextField txtNombreContiene;
    private javax.swing.JTextField txtRuta;
    private javax.swing.JTextField txtlPorcentajeRealizacionDesde;
    private javax.swing.JTextField txtlPorcentajeRealizacionHasta;
    // End of variables declaration//GEN-END:variables

    @Override
    protected void initLiterals() {
        setTitulo();
    }

    @Override
    protected void initListener() {
        initComponents();
        MantenimientoFiltroListener listener = new MantenimientoFiltroListener(this);        
        btnGuardar.addActionListener(listener);
        btnCancelar.addActionListener(listener);
        btnLimpiar.addActionListener(listener);
    }

    @Override
    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    @Override
    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    @Override
    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }
    
    //************************************************
    // Elementos de pantalla
    //*************************************************
    public JButton getBtnRuta() {
        return btnRuta;
    }

    public JCheckBox getChkAnulada() {
        return chkAnulada;
    }

    public JCheckBox getChkCerrada() {
        return chkCerrada;
    }

    public JCheckBox getChkEnCurso() {
        return chkEnCurso;
    }

    public JCheckBox getChkFinalizada() {
        return chkFinalizada;
    }

    public JCheckBox getChkPendiente() {
        return chkPendiente;
    }

    public JCheckBox getChkRetenida() {
        return chkRetenida;
    }

    public JComboBox<Categoria> getCmbCategoria() {
        return cmbCategoria;
    }

    public JComboBox<String> getCmbPeriodoFecha() {
        return cmbPeriodoFecha;
    }

    public JComboBox<Peticion> getCmbPeticion() {
        return cmbPeticion;
    }

    public JComboBox<SubCategoria> getCmbSubCategoria() {
        return cmbSubCategoria;
    }

    public JComboBox<String> getCmbTipoDocumento() {
        return cmbTipoDocumento;
    }

    public JComboBox<String> getCmbTipoHoras() {
        return cmbTipoHoras;
    }

    public JComboBox<Usuario> getCmbUsuario() {
        return cmbUsuario;
    }

    public JTextField getTxtAsuntoContiene() {
        return txtAsuntoContiene;
    }

    public JTextField getTxtFechaFinProgramadoDesde() {
        return txtFechaFinProgramadoDesde;
    }

    public JTextField getTxtFechaFinProgramadoHasta() {
        return txtFechaFinProgramadoHasta;
    }

    public JTextField getTxtFechaFinRealDesde() {
        return txtFechaFinRealDesde;
    }

    public JTextField getTxtFechaFinRealHasta() {
        return txtFechaFinRealHasta;
    }

    public JTextField getTxtFechaImputacionDesde() {
        return txtFechaImputacionDesde;
    }

    public JTextField getTxtFechaImputacionHasta() {
        return txtFechaImputacionHasta;
    }

    public JTextField getTxtFechaInicioProgramadoDesde() {
        return txtFechaInicioProgramadoDesde;
    }

    public JTextField getTxtFechaInicioProgramadoHasta() {
        return txtFechaInicioProgramadoHasta;
    }

    public JTextField getTxtFechaInicioRealDesde() {
        return txtFechaInicioRealDesde;
    }

    public JTextField getTxtFechaInicioRealHasta() {
        return txtFechaInicioRealHasta;
    }

    public JTextField getTxtHorasImputadasDesde() {
        return txtHorasImputadasDesde;
    }

    public JTextField getTxtHorasImputadasHasta() {
        return txtHorasImputadasHasta;
    }

    public JTextField getTxtHorasProgramadasDesde() {
        return txtHorasProgramadasDesde;
    }

    public JTextField getTxtHorasProgramadasHasta() {
        return txtHorasProgramadasHasta;
    }

    public JTextField getTxtHorasRealesDesde() {
        return txtHorasRealesDesde;
    }

    public JTextField getTxtHorasRealesHasta() {
        return txtHorasRealesHasta;
    }

    public JTextField getTxtNombreContiene() {
        return txtNombreContiene;
    }

    public JTextField getTxtRuta() {
        return txtRuta;
    }

    public JTextField getTxtlPorcentajeRealizacionDesde() {
        return txtlPorcentajeRealizacionDesde;
    }

    public JTextField getTxtlPorcentajeRealizacionHasta() {
        return txtlPorcentajeRealizacionHasta;
    }
}
